stm_cms_cms_page:
    resource: "@StmCMSBundle/Resources/config/routing/page.yml"
    prefix:   /cms/page

stm_cms_cms_category:
    resource: "@StmCMSBundle/Resources/config/routing/category.yml"
    prefix:   /cms/category

stm_cms_cms_user:
    resource: "@StmCMSBundle/Resources/config/routing/user.yml"
    prefix:   /cms/user

stm_cms_homepage:
    path:     /
    defaults: { _controller: StmCMSBundle:Default:index }

login:
    path: /login
    defaults: { _controller: StmCMSBundle:Security:login }

login_check:
    path: /login_check

logout:
    pattern: /logout