security:
	encoders:
		Symfony\Component\Security\Core\User: plaintext
		Stm\CMSBundle\Entity\User: bcrypt
	role_hierarchy:
		ROLE_ADMIN: [ROLE_USER]
	providers:
		chain_provider:
			chain:
				providers: [in_memory, user_db]
		in_memory:
			memory:
				users:
					admin:{ password: adminpass, roles: ROLE_ADMIN }
							in_memory:
		user_db:
			entity:{  class: StmCMSBundle:User, property: username }

